//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNorthwindOrders.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNorthwindOrders.Resources.Default", typeof(Default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back To List 的當地語系化字串。
        /// </summary>
        public static string Back_To_List {
            get {
                return ResourceManager.GetString("Back To List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create 的當地語系化字串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create Order 的當地語系化字串。
        /// </summary>
        public static string Create_Order {
            get {
                return ResourceManager.GetString("Create Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customer ID 的當地語系化字串。
        /// </summary>
        public static string Customer_ID {
            get {
                return ResourceManager.GetString("Customer ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Order 的當地語系化字串。
        /// </summary>
        public static string Delete_Order {
            get {
                return ResourceManager.GetString("Delete Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Demo System 的當地語系化字串。
        /// </summary>
        public static string Demo_System {
            get {
                return ResourceManager.GetString("Demo System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Order 的當地語系化字串。
        /// </summary>
        public static string Edit_Order {
            get {
                return ResourceManager.GetString("Edit Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order Date 的當地語系化字串。
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order ID 的當地語系化字串。
        /// </summary>
        public static string Order_ID {
            get {
                return ResourceManager.GetString("Order ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order List 的當地語系化字串。
        /// </summary>
        public static string Order_List {
            get {
                return ResourceManager.GetString("Order List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Required Date 的當地語系化字串。
        /// </summary>
        public static string Required_Date {
            get {
                return ResourceManager.GetString("Required Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ship Address 的當地語系化字串。
        /// </summary>
        public static string Ship_Address {
            get {
                return ResourceManager.GetString("Ship Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ship City 的當地語系化字串。
        /// </summary>
        public static string Ship_City {
            get {
                return ResourceManager.GetString("Ship City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped Date 的當地語系化字串。
        /// </summary>
        public static string Shipped_Date {
            get {
                return ResourceManager.GetString("Shipped Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System Login 的當地語系化字串。
        /// </summary>
        public static string System_Login {
            get {
                return ResourceManager.GetString("System Login", resourceCulture);
            }
        }
    }
}
